describe('Calculator tests', () => {
  it('Application is available', () => {
    cy.visit('/')
  })
  it('Correct navigation', ()=>{
    cy.visit('/')
    cy.get("[data-cy='Settings']").click()
    cy.get("[data-cy='HomeCC']").click()
    cy.get("[data-cy='HomeFC']").click()
  })
  it('Addiction is correct', () => {
    cy.visit('/')
    cy.get("[data-cy='key(1)']").click()
    cy.get("[data-cy='key(+)']").click()
    cy.get("[data-cy='key(2)']").click()
    cy.get("[data-cy='key(=)']").contains("=").click()
    cy.get("[data-cy='calculator-display']").contains("3")
  })
  it('Subtraction is correct', () => {
    cy.visit('/')
    cy.get("[data-cy='key(1)']").click()
    cy.get("[data-cy='key(-)']").click()
    cy.get("[data-cy='key(2)']").click()
    cy.get("[data-cy='key(=)']").contains("=").click()
    cy.get("[data-cy='calculator-display']").contains("-1")
  })
  it('Division is correct', () => {
    cy.visit('/')
    cy.get("[data-cy='key(1)']").click()
    cy.get("[data-cy='key(/)']").click()
    cy.get("[data-cy='key(2)']").click()
    cy.get("[data-cy='key(=)']").contains("=").click()
    cy.get("[data-cy='calculator-display']").contains("0.5")
  })
  it('Multiplication is correct', () => {
    cy.visit('/')
    cy.get("[data-cy='key(1)']").click()
    cy.get("[data-cy='key(*)']").click()
    cy.get("[data-cy='key(2)']").click()
    cy.get("[data-cy='key(=)']").contains("=").click()
    cy.get("[data-cy='calculator-display']").contains("2")
  })

  it('Revers sing with single number is correct', () => {
    cy.visit('/')
    cy.get("[data-cy='key(1)']").click()
    cy.get("[data-cy='key(±)']").click()
    cy.get("[data-cy='calculator-display']").contains("-1")
  })
  it('Revers sing with  expression is correct', () => {
    cy.visit('/')
    cy.get("[data-cy='key(1)']").click()
    cy.get("[data-cy='key(+)']").click()
    cy.get("[data-cy='key(2)']").click()
    cy.get("[data-cy='key(±)']").click()
    cy.get("[data-cy='calculator-display']").contains("1-2")
    cy.get("[data-cy='key(±)']").click()
    cy.get("[data-cy='calculator-display']").contains("1+2")
  })
  it('Display work', () => {
    cy.visit('/')
    cy.get("[data-cy='key(1)']").click()
    cy.get("[data-cy='calculator-display']").contains("1")
    cy.get("[data-cy='key(2)']").click()
    cy.get("[data-cy='calculator-display']").contains("12")
    cy.get("[data-cy='key(3)']").click()
    cy.get("[data-cy='calculator-display']").contains("123")
  })
  it('Theme change is correct', ()=>{
    cy.visit('/')
    cy.get("[data-cy='Settings']").click()
    cy.get("[data-cy='themeSelect']")
      .select('light')
      .select('dark')
  })

})