describe('Calculator tests', () => {
  it('Application is available', () => {
    cy.visit('/')
  })
  it('Correct navigation', ()=>{
    cy.visit('/')
    cy.get("header > div > a[href*=\"settings\"]").click()
    cy.get("header > div > a[href*=\"func/home\"]").click()
    cy.get("header > div > a[href*=\"class/home\"]").click()
  })
  it('Addiction is correct', () => {
    cy.visit('/')
    cy.get("body > div >div > div > div >div").contains("1").click()
    cy.get("body > div >div > div > div >div").contains("+").click()
    cy.get("body > div >div > div > div >div").contains("2").click()
    cy.get("body > div >div > div > div >div").contains("=").click()
    cy.get("body > div >div > div > span").contains("3.000")
  })
  it('Subtraction is correct', () => {
    cy.visit('/')
    cy.get("body > div >div > div > div >div").contains("1").click()
    cy.get("body > div >div > div > div >div").contains("-").click()
    cy.get("body > div >div > div > div >div").contains("2").click()
    cy.get("body > div >div > div > div >div").contains("=").click()
    cy.get("body > div >div > div > span").contains("-1.000")
  })
  it('Division is correct', () => {
    cy.visit('/')
    cy.get("body > div >div > div > div >div").contains("1").click()
    cy.get("body > div >div > div > div >div").contains("/").click()
    cy.get("body > div >div > div > div >div").contains("2").click()
    cy.get("body > div >div > div > div >div").contains("=").click()
    cy.get("body > div >div > div > span").contains("0.500")
  })
  it('Multiplication is correct', () => {
    cy.visit('/')
    cy.get("body > div >div > div > div >div").contains("1").click()
    cy.get("body > div >div > div > div >div").contains("*").click()
    cy.get("body > div >div > div > div >div").contains("2").click()
    cy.get("body > div >div > div > div >div").contains("=").click()
    cy.get("body > div >div > div > span").contains("2.000")
  })

  it('Revers sing with single number is correct', () => {
    cy.visit('/')
    cy.get("body > div >div > div > div >div").contains("1").click()
    cy.get("body > div >div > div > div >div").contains("±").click()
    cy.get("body > div >div > div > span").contains("-1").click()
  })
  it('Revers sing with  expression is correct', () => {
    cy.visit('/')
    cy.get("body > div >div > div > div >div").contains("1").click()
    cy.get("body > div >div > div > div >div").contains("+").click()
    cy.get("body > div >div > div > div >div").contains("2").click()
    cy.get("body > div >div > div > div >div").contains("±").click()
    cy.get("body > div >div > div > span").contains("-(1+2)").click()
    cy.get("body > div >div > div > div >div").contains("±").click()
    cy.get("body > div >div > div > span").contains("1+2").click()
  })
  it('Display work', () => {
    cy.visit('/')
    cy.get("body > div >div > div > div >div").contains("1").click()
    cy.get("body > div >div > div > span").contains("1").click()
    cy.get("body > div >div > div > div >div").contains("2").click()
    cy.get("body > div >div > div > span").contains("12").click()
    cy.get("body > div >div > div > div >div").contains("3").click()
    cy.get("body > div >div > div > span").contains("123").click()
  })
  it('Theme change is correct', ()=>{
    cy.visit('/')
    cy.get("header > div > a[href*=\"settings\"]").click()
    cy.get("select").should("have.value",'dark').select('light').should("have.value",'light')
  })

})